# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f64159b355dbd4ff65d30aef2237ba8590b7f69e19337a46ffaa199ac422e9704b027e79b9499b8ee846a349f755a5f7d29673284e570ca2a1d800bb2cc2a6c

test:
  secret_key_base: 1ad7244dd59510ce828ada16ff9eb27aaeba7ee00c2ecb22e529e449e46f834ace72a323199923be6a2c74ede860c52b4d36eb2045c629a992f07204483e0377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
